apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtuoso-data
  namespace: gmr
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi
  volumeName: virtuoso-data-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtuoso-backup
  namespace: gmr
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 20Gi
  volumeName: virtuoso-backup-pv
  storageClassName: ""
